In [1]:
import numpy as np
from hmmlearn.hmm import MultinomialHMM

In [2]:
path="HomeworkData/"
seq = np.load(path+"sequences.npy")

In [9]:
model = MultinomialHMM(n_components=2,n_iter=1000) 
model.startprob_ = 1/2*np.ones(2)
model.transmat_ = 1/2*np.ones((2,2)) 
model.emissionprob_ = 1/6*np.ones((2,6)) 
model.fit(seq.reshape(-1,1)-1,lengths=(30*np.ones(200)).astype(np.uint8))

MultinomialHMM(algorithm='viterbi', init_params='ste', n_components=2,
               n_iter=1000, params='ste',
               random_state=RandomState(MT19937) at 0x114CFE9E0,
               startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
               verbose=False)

In [10]:
np.set_printoptions(precision=4,suppress=True)

pi = model.startprob_
A = model.transmat_
E = model.emissionprob_

print(pi)
print(A)
print(E)

[0.3599 0.6401]
[[0.9079 0.0921]
 [0.0564 0.9436]]
[[0.105  0.1033 0.0954 0.0956 0.1037 0.4969]
 [0.1647 0.1566 0.1789 0.1746 0.1753 0.1499]]


In [11]:
def foreward(pi,A,e):
    alpha = e*pi
    print("alpha_1:",alpha)
    for i in range(3):
        alpha = e*np.dot(A.T,alpha)
        print("alpha_%d:"%(i+2),alpha)
    prob = np.sum(alpha)
    print("prob:",prob)

def backward(pi,A,e):
    beta = np.ones(2)
    print("beta_4:",beta)
    for i in range(3):
        beta = np.dot(A, e*beta)
        print("beta_%d:"%(3-i),beta)
    prob = np.dot(pi,e*beta)
    print("prob:",prob)

In [12]:
e = np.array([E[0,5],E[1,5]])
foreward(pi,A,e)
backward(pi,A,e)

alpha_1: [0.1789 0.0959]
alpha_2: [0.0834 0.016 ]
alpha_3: [0.0381 0.0034]
alpha_4: [0.0173 0.001 ]
prob: 0.0182793425451436
beta_4: [1. 1.]
beta_3: [0.465  0.1694]
beta_2: [0.2121 0.037 ]
beta_1: [0.0962 0.0112]
prob: 0.0182793425451436


In [13]:
obs = (np.array([3,2,1,3,4,5,6,3,1,4,1,6,6,2,6]).reshape(-1,1))-1
log_prob, state_seq = model.decode(obs)
print(state_seq)

[1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
